services:
  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: prometheus
    ports:
      - "9091:9090"
    networks:
      - taxi-network

  grafana:
    image: grafana/grafana:10.2.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    networks:
      - taxi-network

  redis:
    image: redis:7-alpine
    container_name: taxi-redis
    ports:
      - "6379:6379"
    networks:
      - taxi-network

networks:
  taxi-network:
    external: true